elasticsearch:
  version: "v7"
  logLevel: "error"
  url:
    scheme: "https"
    host: "vpc-es-bench-74hq6hbgws6kddcgyhqn53c3om.us-east-1.es.amazonaws.com"
#    host: "vpc-hollywood-egvqsfkoo5tbou74x7oto6dk5a.us-east-1.es.amazonaws.com"
  username: "temporal"
  password: ""
  indices:
    visibility: "es_bench_v1_hollywood_sorted"

processor:
  indexConcurrency: 100
  numOfWorkers: 1
  bulkActions: 500
  bulkSize: 16777216
  flushInterval: 1s
  ackTimeout: 1m

metrics:
  prometheus:
    timerType: "histogram"
    listenAddress: "0.0.0.0:8000"
