elasticsearch:
  version: "v7"
  logLevel: "error"
  url:
    scheme: "https"
    host: "vpc-hollywood-egvqsfkoo5tbou74x7oto6dk5a.us-east-1.es.amazonaws.com"
  username: "temporal"
  password: ""
  indices:
    visibility: "temporal_es_bench_v1_hollywood"

processor:
  indexConcurrency: 100
  numOfWorkers: 4
  bulkActions: 500
  bulkSize: 65777216
  flushInterval: 1s
  ackTimeout: 1m

metrics:
  prometheus:
    timerType: "histogram"
    listenAddress: "0.0.0.0:8000"
